### PR TITLE
fix(geocoder): return correct error messages

### PR DESCRIPTION
**Pull request by Caerostris**
The error messages currently returned assume that errors can only occur due to incorrect credentials.
This PR adds error messages for DNS errors, IP errors, and unknown errors.

### CODE REVIEW

**Comment by aemkei** [comment]
Looks good, but please fix the CI first.

**Comment by Caerostris** [comment]
Part of the reason why the tests are failing is that the file `test/helpers-test.js` does not pass the linter.
I haven't touched the file in this PR, so I think it would be cleaner to open a separate PR for that.
That being said, I forgot to update the test cases.

**Comment by aemkei** [comment]
Looks good to me.
@ro-ka Can you have a look, too?

**Comment by ro-ka** [comment]
:shipit:

**Pull request merged**
